/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import OrderWsDTOModel from '../models/OrderWsDTOModel';

/**
* Orders service.
* @module api/OrdersApi
* @version v2
*/
export default class OrdersApi {

    /**
    * Constructs a new OrdersApi. 
    * @alias module:api/OrdersApi
    * @class
    * @param {module:ApiClient} apiClient Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * getOrder
     * Returns details of a specific order based on order GUID (Globally Unique Identifier) or order CODE. The response contains a detailed order information.  Security: Allowed only for trusted client 
     * @param {String} code Order GUID (Globally Unique Identifier) or order CODE
     * @param {Object} opts Optional parameters
     * @param {String} opts.fields Response configuration (list of fields, which should be returned in response)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/OrderWsDTOModel} and HTTP response
     */
    ordersByCodeWithHttpInfo(code, opts) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'code' is set
      if (code === undefined || code === null) {
        throw new Error("Missing the required parameter 'code' when calling getOrder");
      }


      let pathParams = {
        'code': code
      };
      let queryParams = {
        'fields': opts['fields']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OrderWsDTOModel;

      return this.apiClient.callApi(
        '/orders/{code}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * getOrder
     * Returns details of a specific order based on order GUID (Globally Unique Identifier) or order CODE. The response contains a detailed order information.  Security: Allowed only for trusted client 
     * @param {String} code Order GUID (Globally Unique Identifier) or order CODE
     * @param {Object} opts Optional parameters
     * @param {String} opts.fields Response configuration (list of fields, which should be returned in response)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/OrderWsDTOModel}
     */
    getOrder(code, opts) {
      return this.ordersByCodeWithHttpInfo(code, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
