/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
    // AMD.
        define(['expect.js', '../../src/index'], factory)
    } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require('../../src/index'))
    } else {
    // Browser globals (root is window)
        factory(root.expect, root.Occ)
    }
}(this, (expect, Occ) => {
    'use strict'

    let instance

    beforeEach(() => {
        instance = new Occ.Breadcrumb()
    })

    const getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function') { return object[getter]() } else { return object[property] }
    }

    const setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function') { object[setter](value) } else { object[property] = value }
    }

    describe('Breadcrumb', () => {
        it('should create an instance of Breadcrumb', () => {
            // uncomment below and update the code to test Breadcrumb
            // var instane = new Occ.Breadcrumb();
            // expect(instance).to.be.a(Occ.Breadcrumb);
        })

        it('should have the property facetCode (base name: "facetCode")', () => {
            // uncomment below and update the code to test the property facetCode
            // var instane = new Occ.Breadcrumb();
            // expect(instance).to.be();
        })

        it('should have the property facetName (base name: "facetName")', () => {
            // uncomment below and update the code to test the property facetName
            // var instane = new Occ.Breadcrumb();
            // expect(instance).to.be();
        })

        it('should have the property facetValueCode (base name: "facetValueCode")', () => {
            // uncomment below and update the code to test the property facetValueCode
            // var instane = new Occ.Breadcrumb();
            // expect(instance).to.be();
        })

        it('should have the property facetValueName (base name: "facetValueName")', () => {
            // uncomment below and update the code to test the property facetValueName
            // var instane = new Occ.Breadcrumb();
            // expect(instance).to.be();
        })

        it('should have the property removeQuery (base name: "removeQuery")', () => {
            // uncomment below and update the code to test the property removeQuery
            // var instane = new Occ.Breadcrumb();
            // expect(instance).to.be();
        })

        it('should have the property truncateQuery (base name: "truncateQuery")', () => {
            // uncomment below and update the code to test the property truncateQuery
            // var instane = new Occ.Breadcrumb();
            // expect(instance).to.be();
        })

    })

}))
