/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Occ);
  }
}(this, function(expect, Occ) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Occ.ConsignmentWsDTOModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConsignmentWsDTOModel', function() {
    it('should create an instance of ConsignmentWsDTOModel', function() {
      // uncomment below and update the code to test ConsignmentWsDTOModel
      //var instane = new Occ.ConsignmentWsDTOModel();
      //expect(instance).to.be.a(Occ.ConsignmentWsDTOModel);
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instane = new Occ.ConsignmentWsDTOModel();
      //expect(instance).to.be();
    });

    it('should have the property trackingID (base name: "trackingID")', function() {
      // uncomment below and update the code to test the property trackingID
      //var instane = new Occ.ConsignmentWsDTOModel();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new Occ.ConsignmentWsDTOModel();
      //expect(instance).to.be();
    });

    it('should have the property statusDate (base name: "statusDate")', function() {
      // uncomment below and update the code to test the property statusDate
      //var instane = new Occ.ConsignmentWsDTOModel();
      //expect(instance).to.be();
    });

    it('should have the property entries (base name: "entries")', function() {
      // uncomment below and update the code to test the property entries
      //var instane = new Occ.ConsignmentWsDTOModel();
      //expect(instance).to.be();
    });

    it('should have the property shippingAddress (base name: "shippingAddress")', function() {
      // uncomment below and update the code to test the property shippingAddress
      //var instane = new Occ.ConsignmentWsDTOModel();
      //expect(instance).to.be();
    });

    it('should have the property deliveryPointOfService (base name: "deliveryPointOfService")', function() {
      // uncomment below and update the code to test the property deliveryPointOfService
      //var instane = new Occ.ConsignmentWsDTOModel();
      //expect(instance).to.be();
    });

  });

}));
