/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
    // AMD.
        define(['expect.js', '../../src/index'], factory)
    } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require('../../src/index'))
    } else {
    // Browser globals (root is window)
        factory(root.expect, root.Occ)
    }
}(this, (expect, Occ) => {
    'use strict'

    let instance

    beforeEach(() => {
        instance = new Occ.OrderHistoryListWsDTO()
    })

    const getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function') { return object[getter]() } else { return object[property] }
    }

    const setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function') { object[setter](value) } else { object[property] = value }
    }

    describe('OrderHistoryListWsDTO', () => {
        it('should create an instance of OrderHistoryListWsDTO', () => {
            // uncomment below and update the code to test OrderHistoryListWsDTO
            // var instane = new Occ.OrderHistoryListWsDTO();
            // expect(instance).to.be.a(Occ.OrderHistoryListWsDTO);
        })

        it('should have the property orders (base name: "orders")', () => {
            // uncomment below and update the code to test the property orders
            // var instane = new Occ.OrderHistoryListWsDTO();
            // expect(instance).to.be();
        })

        it('should have the property sorts (base name: "sorts")', () => {
            // uncomment below and update the code to test the property sorts
            // var instane = new Occ.OrderHistoryListWsDTO();
            // expect(instance).to.be();
        })

        it('should have the property pagination (base name: "pagination")', () => {
            // uncomment below and update the code to test the property pagination
            // var instane = new Occ.OrderHistoryListWsDTO();
            // expect(instance).to.be();
        })

    })

}))
