/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Occ);
  }
}(this, function(expect, Occ) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Occ.PickupOrderEntryGroupWsDTOModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PickupOrderEntryGroupWsDTOModel', function() {
    it('should create an instance of PickupOrderEntryGroupWsDTOModel', function() {
      // uncomment below and update the code to test PickupOrderEntryGroupWsDTOModel
      //var instane = new Occ.PickupOrderEntryGroupWsDTOModel();
      //expect(instance).to.be.a(Occ.PickupOrderEntryGroupWsDTOModel);
    });

    it('should have the property deliveryPointOfService (base name: "deliveryPointOfService")', function() {
      // uncomment below and update the code to test the property deliveryPointOfService
      //var instane = new Occ.PickupOrderEntryGroupWsDTOModel();
      //expect(instance).to.be();
    });

    it('should have the property distance (base name: "distance")', function() {
      // uncomment below and update the code to test the property distance
      //var instane = new Occ.PickupOrderEntryGroupWsDTOModel();
      //expect(instance).to.be();
    });

    it('should have the property totalPriceWithTax (base name: "totalPriceWithTax")', function() {
      // uncomment below and update the code to test the property totalPriceWithTax
      //var instane = new Occ.PickupOrderEntryGroupWsDTOModel();
      //expect(instance).to.be();
    });

    it('should have the property entries (base name: "entries")', function() {
      // uncomment below and update the code to test the property entries
      //var instane = new Occ.PickupOrderEntryGroupWsDTOModel();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instane = new Occ.PickupOrderEntryGroupWsDTOModel();
      //expect(instance).to.be();
    });

  });

}));
