/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import Address from './Address'

/**
* The AddressList model module.
* @module models/AddressList
* @version v2
*/
export default class AddressList {
    /**
    * Constructs a new <code>AddressList</code>.
    * @alias module:models/AddressList
    * @class
    */

    constructor() {
        /**
        *
        * @member {Array.<module:models/Address>} addresses
        */
        this.addresses = undefined
    }

    /**
    * Constructs a <code>AddressList</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/AddressList} obj Optional instance to populate.
    * @return {module:models/AddressList} The populated
    * <code>AddressList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressList()

            if (data.hasOwnProperty('addresses')) {
                obj.addresses = ApiClient.convertToType(data.addresses, [Address])
            }
        }
        return obj
    }
}
