/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import AddressWsDTO from './AddressWsDTO'

/**
* The AddressListWsDTO model module.
* @module models/AddressListWsDTO
* @version v2
*/
export default class AddressListWsDTO {
    /**
    * Constructs a new <code>AddressListWsDTO</code>.
    * @alias module:models/AddressListWsDTO
    * @class
    */

    constructor() {
        /**
        *
        * @member {Array.<module:models/AddressWsDTO>} addresses
        */
        this.addresses = undefined
    }

    /**
    * Constructs a <code>AddressListWsDTO</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/AddressListWsDTO} obj Optional instance to populate.
    * @return {module:models/AddressListWsDTO} The populated
    * <code>AddressListWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressListWsDTO()

            if (data.hasOwnProperty('addresses')) {
                obj.addresses = ApiClient.convertToType(data.addresses, [AddressWsDTO])
            }
        }
        return obj
    }
}
