/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient';
import VariantOptionWsDTO from './VariantOptionWsDTO';

/**
* The BaseOptionWsDTO model module.
* @module models/BaseOptionWsDTO
* @version v2
*/
export default class BaseOptionWsDTO {
    /**
    * Constructs a new <code>BaseOptionWsDTO</code>.
    * @alias module:models/BaseOptionWsDTO
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>BaseOptionWsDTO</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/BaseOptionWsDTO} obj Optional instance to populate.
    * @return {module:models/BaseOptionWsDTO} The populated
    * <code>BaseOptionWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BaseOptionWsDTO();

            if (data.hasOwnProperty('variantType')) {
                obj['variantType'] = ApiClient.convertToType(data['variantType'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], [VariantOptionWsDTO]);
            }
            if (data.hasOwnProperty('selected')) {
                obj['selected'] = VariantOptionWsDTO.constructFromObject(data['selected']);
            }
        }
        return obj;
    }

    /**
    * 
    * @member {String} variantType
    */
    variantType = undefined;
    /**
    * 
    * @member {Array.<module:models/VariantOptionWsDTO>} options
    */
    options = undefined;
    /**
    * @member {module:models/VariantOptionWsDTO} selected
    */
    selected = undefined;

}
