/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import SearchState from './SearchState'

/**
* The Breadcrumb model module.
* @module models/Breadcrumb
* @version v2
*/
export default class Breadcrumb {
    /**
    * Constructs a new <code>Breadcrumb</code>.
    * @alias module:models/Breadcrumb
    * @class
    */

    constructor() {
        /**
    *
    * @member {String} facetCode
    */
        this.facetCode = undefined
        /**
    *
    * @member {String} facetName
    */
        this.facetName = undefined
        /**
    *
    * @member {String} facetValueCode
    */
        this.facetValueCode = undefined
        /**
    *
    * @member {String} facetValueName
    */
        this.facetValueName = undefined
        /**
    * @member {module:models/SearchState} removeQuery
    */
        this.removeQuery = undefined
        /**
    * @member {module:models/SearchState} truncateQuery
    */
        this.truncateQuery = undefined
    }

    /**
    * Constructs a <code>Breadcrumb</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/Breadcrumb} obj Optional instance to populate.
    * @return {module:models/Breadcrumb} The populated
    * <code>Breadcrumb</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Breadcrumb()

            if (data.hasOwnProperty('facetCode')) {
                obj.facetCode = ApiClient.convertToType(data.facetCode, 'String')
            }
            if (data.hasOwnProperty('facetName')) {
                obj.facetName = ApiClient.convertToType(data.facetName, 'String')
            }
            if (data.hasOwnProperty('facetValueCode')) {
                obj.facetValueCode = ApiClient.convertToType(data.facetValueCode, 'String')
            }
            if (data.hasOwnProperty('facetValueName')) {
                obj.facetValueName = ApiClient.convertToType(data.facetValueName, 'String')
            }
            if (data.hasOwnProperty('removeQuery')) {
                obj.removeQuery = SearchState.constructFromObject(data.removeQuery)
            }
            if (data.hasOwnProperty('truncateQuery')) {
                obj.truncateQuery = SearchState.constructFromObject(data.truncateQuery)
            }
        }
        return obj
    }

}
