/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient';
import SearchStateWsDTO from './SearchStateWsDTO';

/**
* The BreadcrumbWsDTO model module.
* @module models/BreadcrumbWsDTO
* @version v2
*/
export default class BreadcrumbWsDTO {
    /**
    * Constructs a new <code>BreadcrumbWsDTO</code>.
    * @alias module:models/BreadcrumbWsDTO
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>BreadcrumbWsDTO</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/BreadcrumbWsDTO} obj Optional instance to populate.
    * @return {module:models/BreadcrumbWsDTO} The populated
    * <code>BreadcrumbWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BreadcrumbWsDTO();

            if (data.hasOwnProperty('facetCode')) {
                obj['facetCode'] = ApiClient.convertToType(data['facetCode'], 'String');
            }
            if (data.hasOwnProperty('facetName')) {
                obj['facetName'] = ApiClient.convertToType(data['facetName'], 'String');
            }
            if (data.hasOwnProperty('facetValueCode')) {
                obj['facetValueCode'] = ApiClient.convertToType(data['facetValueCode'], 'String');
            }
            if (data.hasOwnProperty('facetValueName')) {
                obj['facetValueName'] = ApiClient.convertToType(data['facetValueName'], 'String');
            }
            if (data.hasOwnProperty('removeQuery')) {
                obj['removeQuery'] = SearchStateWsDTO.constructFromObject(data['removeQuery']);
            }
            if (data.hasOwnProperty('truncateQuery')) {
                obj['truncateQuery'] = SearchStateWsDTO.constructFromObject(data['truncateQuery']);
            }
        }
        return obj;
    }

    /**
    * 
    * @member {String} facetCode
    */
    facetCode = undefined;
    /**
    * 
    * @member {String} facetName
    */
    facetName = undefined;
    /**
    * 
    * @member {String} facetValueCode
    */
    facetValueCode = undefined;
    /**
    * 
    * @member {String} facetValueName
    */
    facetValueName = undefined;
    /**
    * @member {module:models/SearchStateWsDTO} removeQuery
    */
    removeQuery = undefined;
    /**
    * @member {module:models/SearchStateWsDTO} truncateQuery
    */
    truncateQuery = undefined;

}
