/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SearchStateWsDTOModel from './SearchStateWsDTOModel';

/**
* The BreadcrumbWsDTOModel model module.
* @module models/BreadcrumbWsDTOModel
* @version v2
*/
export default class BreadcrumbWsDTOModel {
    /**
    * Constructs a new <code>BreadcrumbWsDTOModel</code>.
    * @alias module:models/BreadcrumbWsDTOModel
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>BreadcrumbWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/BreadcrumbWsDTOModel} obj Optional instance to populate.
    * @return {module:models/BreadcrumbWsDTOModel} The populated <code>BreadcrumbWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BreadcrumbWsDTOModel();

            if (data.hasOwnProperty('facetCode')) {
                obj['facetCode'] = ApiClient.convertToType(data['facetCode'], 'String');
            }
            if (data.hasOwnProperty('facetName')) {
                obj['facetName'] = ApiClient.convertToType(data['facetName'], 'String');
            }
            if (data.hasOwnProperty('facetValueCode')) {
                obj['facetValueCode'] = ApiClient.convertToType(data['facetValueCode'], 'String');
            }
            if (data.hasOwnProperty('facetValueName')) {
                obj['facetValueName'] = ApiClient.convertToType(data['facetValueName'], 'String');
            }
            if (data.hasOwnProperty('removeQuery')) {
                obj['removeQuery'] = SearchStateWsDTOModel.constructFromObject(data['removeQuery']);
            }
            if (data.hasOwnProperty('truncateQuery')) {
                obj['truncateQuery'] = SearchStateWsDTOModel.constructFromObject(data['truncateQuery']);
            }
        }
        return obj;
    }

    /**
    * 
    * @member {String} facetCode
    */
    facetCode = undefined;
    /**
    * 
    * @member {String} facetName
    */
    facetName = undefined;
    /**
    * 
    * @member {String} facetValueCode
    */
    facetValueCode = undefined;
    /**
    * 
    * @member {String} facetValueName
    */
    facetValueName = undefined;
    /**
    * @member {module:models/SearchStateWsDTOModel} removeQuery
    */
    removeQuery = undefined;
    /**
    * @member {module:models/SearchStateWsDTOModel} truncateQuery
    */
    truncateQuery = undefined;

}
