/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import CardType from './CardType'

/**
* The CardTypeList model module.
* @module models/CardTypeList
* @version v2
*/
export default class CardTypeList {
    /**
    * Constructs a new <code>CardTypeList</code>.
    * @alias module:models/CardTypeList
    * @class
    */

    constructor() {
        /**
    *
    * @member {Array.<module:models/CardType>} cardTypes
    */
        this.cardTypes = undefined
    }

    /**
    * Constructs a <code>CardTypeList</code> from a plain JavaScript
    * object, optionally creating a new instance. Copies all relevant properties
    * from <code>data</code> to <code>obj</code> if supplied or a new instance
    * if not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/CardTypeList} obj Optional instance to
    * populate.
    * @return {module:models/CardTypeList} The populated
    * <code>CardTypeList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CardTypeList()

            if (data.hasOwnProperty('cardTypes')) {
                obj.cardTypes = ApiClient.convertToType(data.cardTypes, [CardType])
            }
        }
        return obj
    }

}
