/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import CartWsDTOModel from './CartWsDTOModel';





/**
* The CartListWsDTOModel model module.
* @module models/CartListWsDTOModel
* @version v2
*/
export default class CartListWsDTOModel {
    /**
    * Constructs a new <code>CartListWsDTOModel</code>.
    * @alias module:models/CartListWsDTOModel
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>CartListWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CartListWsDTOModel} obj Optional instance to populate.
    * @return {module:models/CartListWsDTOModel} The populated <code>CartListWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartListWsDTOModel();

            
            
            

            if (data.hasOwnProperty('carts')) {
                obj['carts'] = ApiClient.convertToType(data['carts'], [CartWsDTOModel]);
            }
        }
        return obj;
    }

    /**
    * 
    * @member {Array.<module:models/CartWsDTOModel>} carts
    */
    carts = undefined;








}


