/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import AddressWsDTO from './AddressWsDTO'
import DeliveryModeWsDTO from './DeliveryModeWsDTO'
import DeliveryOrderEntryGroupWsDTO from './DeliveryOrderEntryGroupWsDTO'
import OrderEntryWsDTO from './OrderEntryWsDTO'
import PaymentDetailsWsDTO from './PaymentDetailsWsDTO'
import PickupOrderEntryGroupWsDTO from './PickupOrderEntryGroupWsDTO'
import PriceWsDTO from './PriceWsDTO'
import PrincipalWsDTO from './PrincipalWsDTO'
import PromotionResultWsDTO from './PromotionResultWsDTO'
import VoucherWsDTO from './VoucherWsDTO'

/**
* The CartWsDTO model module.
* @module models/CartWsDTO
* @version v2
*/
export default class CartWsDTO {
    /**
    * Constructs a new <code>CartWsDTO</code>.
    * @alias module:models/CartWsDTO
    * @class
    */

    constructor() {
        /**
    *
    * @member {Number} totalUnitCount
    */
        this.totalUnitCount = undefined
        /**
    *
    * @member {Array.<module:models/PromotionResultWsDTO>}
    * potentialOrderPromotions
    */
        this.potentialOrderPromotions = undefined
        /**
    *
    * @member {Array.<module:models/PromotionResultWsDTO>}
    * potentialProductPromotions
    */
        this.potentialProductPromotions = undefined
        /**
    *
    * @member {String} name
    */
        this.name = undefined
        /**
    *
    * @member {String} description
    */
        this.description = undefined
        /**
    *
    * @member {String} expirationTime
    */
        this.expirationTime = undefined
        /**
    *
    * @member {String} saveTime
    */
        this.saveTime = undefined
        /**
    * @member {module:models/PrincipalWsDTO} savedBy
    */
        this.savedBy = undefined
        /**
    *
    * @member {String} code
    */
        this.code = undefined
        /**
    *
    * @member {Boolean} net
    */
        this.net = undefined
        /**
    * @member {module:models/PriceWsDTO} totalPriceWithTax
    */
        this.totalPriceWithTax = undefined
        /**
    * @member {module:models/PriceWsDTO} totalPrice
    */
        this.totalPrice = undefined
        /**
    * @member {module:models/PriceWsDTO} totalTax
    */
        this.totalTax = undefined
        /**
    * @member {module:models/PriceWsDTO} subTotal
    */
        this.subTotal = undefined
        /**
    * @member {module:models/PriceWsDTO} deliveryCost
    */
        this.deliveryCost = undefined
        /**
    *
    * @member {Array.<module:models/OrderEntryWsDTO>} entries
    */
        this.entries = undefined
        /**
    *
    * @member {Number} totalItems
    */
        this.totalItems = undefined
        /**
    * @member {module:models/DeliveryModeWsDTO} deliveryMode
    */
        this.deliveryMode = undefined
        /**
    * @member {module:models/AddressWsDTO} deliveryAddress
    */
        this.deliveryAddress = undefined
        /**
    * @member {module:models/PaymentDetailsWsDTO} paymentInfo
    */
        this.paymentInfo = undefined
        /**
    *
    * @member {Array.<module:models/PromotionResultWsDTO>}
    * appliedOrderPromotions
    */
        this.appliedOrderPromotions = undefined
        /**
    *
    * @member {Array.<module:models/PromotionResultWsDTO>}
    * appliedProductPromotions
    */
        this.appliedProductPromotions = undefined
        /**
    * @member {module:models/PriceWsDTO} productDiscounts
    */
        this.productDiscounts = undefined
        /**
    * @member {module:models/PriceWsDTO} orderDiscounts
    */
        this.orderDiscounts = undefined
        /**
    * @member {module:models/PriceWsDTO} totalDiscounts
    */
        this.totalDiscounts = undefined
        /**
    *
    * @member {String} site
    */
        this.site = undefined
        /**
    *
    * @member {String} store
    */
        this.store = undefined
        /**
    *
    * @member {String} guid
    */
        this.guid = undefined
        /**
    *
    * @member {Boolean} calculated
    */
        this.calculated = undefined
        /**
    *
    * @member {Array.<module:models/VoucherWsDTO>} appliedVouchers
    */
        this.appliedVouchers = undefined
        /**
    * @member {module:models/PrincipalWsDTO} user
    */
        this.user = undefined
        /**
    *
    * @member {Array.<module:models/PickupOrderEntryGroupWsDTO>}
    * pickupOrderGroups
    */
        this.pickupOrderGroups = undefined
        /**
    *
    * @member {Array.<module:models/DeliveryOrderEntryGroupWsDTO>}
    * deliveryOrderGroups
    */
        this.deliveryOrderGroups = undefined
        /**
    *
    * @member {Number} pickupItemsQuantity
    */
        this.pickupItemsQuantity = undefined
        /**
    *
    * @member {Number} deliveryItemsQuantity
    */
        this.deliveryItemsQuantity = undefined
    }

    /**
    * Constructs a <code>CartWsDTO</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/CartWsDTO} obj Optional instance to populate.
    * @return {module:models/CartWsDTO} The populated <code>CartWsDTO</code>
    * instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartWsDTO()

            if (data.hasOwnProperty('totalUnitCount')) {
                obj.totalUnitCount = ApiClient.convertToType(data.totalUnitCount, 'Number')
            }
            if (data.hasOwnProperty('potentialOrderPromotions')) {
                obj.potentialOrderPromotions = ApiClient.convertToType(data.potentialOrderPromotions, [PromotionResultWsDTO])
            }
            if (data.hasOwnProperty('potentialProductPromotions')) {
                obj.potentialProductPromotions = ApiClient.convertToType(data.potentialProductPromotions, [PromotionResultWsDTO])
            }
            if (data.hasOwnProperty('name')) {
                obj.name = ApiClient.convertToType(data.name, 'String')
            }
            if (data.hasOwnProperty('description')) {
                obj.description = ApiClient.convertToType(data.description, 'String')
            }
            if (data.hasOwnProperty('expirationTime')) {
                obj.expirationTime = ApiClient.convertToType(data.expirationTime, 'String')
            }
            if (data.hasOwnProperty('saveTime')) {
                obj.saveTime = ApiClient.convertToType(data.saveTime, 'String')
            }
            if (data.hasOwnProperty('savedBy')) {
                obj.savedBy = PrincipalWsDTO.constructFromObject(data.savedBy)
            }
            if (data.hasOwnProperty('code')) {
                obj.code = ApiClient.convertToType(data.code, 'String')
            }
            if (data.hasOwnProperty('net')) {
                obj.net = ApiClient.convertToType(data.net, 'Boolean')
            }
            if (data.hasOwnProperty('totalPriceWithTax')) {
                obj.totalPriceWithTax = PriceWsDTO.constructFromObject(data.totalPriceWithTax)
            }
            if (data.hasOwnProperty('totalPrice')) {
                obj.totalPrice = PriceWsDTO.constructFromObject(data.totalPrice)
            }
            if (data.hasOwnProperty('totalTax')) {
                obj.totalTax = PriceWsDTO.constructFromObject(data.totalTax)
            }
            if (data.hasOwnProperty('subTotal')) {
                obj.subTotal = PriceWsDTO.constructFromObject(data.subTotal)
            }
            if (data.hasOwnProperty('deliveryCost')) {
                obj.deliveryCost = PriceWsDTO.constructFromObject(data.deliveryCost)
            }
            if (data.hasOwnProperty('entries')) {
                obj.entries = ApiClient.convertToType(data.entries, [OrderEntryWsDTO])
            }
            if (data.hasOwnProperty('totalItems')) {
                obj.totalItems = ApiClient.convertToType(data.totalItems, 'Number')
            }
            if (data.hasOwnProperty('deliveryMode')) {
                obj.deliveryMode = DeliveryModeWsDTO.constructFromObject(data.deliveryMode)
            }
            if (data.hasOwnProperty('deliveryAddress')) {
                obj.deliveryAddress = AddressWsDTO.constructFromObject(data.deliveryAddress)
            }
            if (data.hasOwnProperty('paymentInfo')) {
                obj.paymentInfo = PaymentDetailsWsDTO.constructFromObject(data.paymentInfo)
            }
            if (data.hasOwnProperty('appliedOrderPromotions')) {
                obj.appliedOrderPromotions = ApiClient.convertToType(data.appliedOrderPromotions, [PromotionResultWsDTO])
            }
            if (data.hasOwnProperty('appliedProductPromotions')) {
                obj.appliedProductPromotions = ApiClient.convertToType(data.appliedProductPromotions, [PromotionResultWsDTO])
            }
            if (data.hasOwnProperty('productDiscounts')) {
                obj.productDiscounts = PriceWsDTO.constructFromObject(data.productDiscounts)
            }
            if (data.hasOwnProperty('orderDiscounts')) {
                obj.orderDiscounts = PriceWsDTO.constructFromObject(data.orderDiscounts)
            }
            if (data.hasOwnProperty('totalDiscounts')) {
                obj.totalDiscounts = PriceWsDTO.constructFromObject(data.totalDiscounts)
            }
            if (data.hasOwnProperty('site')) {
                obj.site = ApiClient.convertToType(data.site, 'String')
            }
            if (data.hasOwnProperty('store')) {
                obj.store = ApiClient.convertToType(data.store, 'String')
            }
            if (data.hasOwnProperty('guid')) {
                obj.guid = ApiClient.convertToType(data.guid, 'String')
            }
            if (data.hasOwnProperty('calculated')) {
                obj.calculated = ApiClient.convertToType(data.calculated, 'Boolean')
            }
            if (data.hasOwnProperty('appliedVouchers')) {
                obj.appliedVouchers = ApiClient.convertToType(data.appliedVouchers, [VoucherWsDTO])
            }
            if (data.hasOwnProperty('user')) {
                obj.user = PrincipalWsDTO.constructFromObject(data.user)
            }
            if (data.hasOwnProperty('pickupOrderGroups')) {
                obj.pickupOrderGroups = ApiClient.convertToType(data.pickupOrderGroups, [PickupOrderEntryGroupWsDTO])
            }
            if (data.hasOwnProperty('deliveryOrderGroups')) {
                obj.deliveryOrderGroups = ApiClient.convertToType(data.deliveryOrderGroups, [DeliveryOrderEntryGroupWsDTO])
            }
            if (data.hasOwnProperty('pickupItemsQuantity')) {
                obj.pickupItemsQuantity = ApiClient.convertToType(data.pickupItemsQuantity, 'Number')
            }
            if (data.hasOwnProperty('deliveryItemsQuantity')) {
                obj.deliveryItemsQuantity = ApiClient.convertToType(data.deliveryItemsQuantity, 'Number')
            }
        }
        return obj
    }

}
