/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CategoryHierarchyWsDTOModel model module.
* @module models/CategoryHierarchyWsDTOModel
* @version v2
*/
export default class CategoryHierarchyWsDTOModel {
    /**
    * Constructs a new <code>CategoryHierarchyWsDTOModel</code>.
    * @alias module:models/CategoryHierarchyWsDTOModel
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>CategoryHierarchyWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CategoryHierarchyWsDTOModel} obj Optional instance to populate.
    * @return {module:models/CategoryHierarchyWsDTOModel} The populated <code>CategoryHierarchyWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategoryHierarchyWsDTOModel();

        }
        return obj;
    }

}
