/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import FeatureWsDTO from './FeatureWsDTO'

/**
* The ClassificationWsDTO model module.
* @module models/ClassificationWsDTO
* @version v2
*/
export default class ClassificationWsDTO {
    /**
    * Constructs a new <code>ClassificationWsDTO</code>.
    * @alias module:models/ClassificationWsDTO
    * @class
    */

    constructor() {
        /**
    *
    * @member {String} code
    */
        this.code = undefined
        /**
    *
    * @member {String} name
    */
        this.name = undefined
        /**
    *
    * @member {Array.<module:models/FeatureWsDTO>} features
    */
        this.features = undefined
    }

    /**
    * Constructs a <code>ClassificationWsDTO</code> from a plain JavaScript
    * object, optionally creating a new instance. Copies all relevant properties
    * from <code>data</code> to <code>obj</code> if supplied or a new instance
    * if not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/ClassificationWsDTO} obj Optional instance to
    * populate.
    * @return {module:models/ClassificationWsDTO} The populated
    * <code>ClassificationWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClassificationWsDTO()

            if (data.hasOwnProperty('code')) {
                obj.code = ApiClient.convertToType(data.code, 'String')
            }
            if (data.hasOwnProperty('name')) {
                obj.name = ApiClient.convertToType(data.name, 'String')
            }
            if (data.hasOwnProperty('features')) {
                obj.features = ApiClient.convertToType(data.features, [FeatureWsDTO])
            }
        }
        return obj
    }

}
