/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CountryWsDTOModel from './CountryWsDTOModel';

/**
* The CountryListWsDTOModel model module.
* @module models/CountryListWsDTOModel
* @version v2
*/
export default class CountryListWsDTOModel {
    /**
    * Constructs a new <code>CountryListWsDTOModel</code>.
    * @alias module:models/CountryListWsDTOModel
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>CountryListWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CountryListWsDTOModel} obj Optional instance to populate.
    * @return {module:models/CountryListWsDTOModel} The populated <code>CountryListWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CountryListWsDTOModel();

            if (data.hasOwnProperty('countries')) {
                obj['countries'] = ApiClient.convertToType(data['countries'], [CountryWsDTOModel]);
            }
        }
        return obj;
    }

    /**
    * 
    * @member {Array.<module:models/CountryWsDTOModel>} countries
    */
    countries = undefined;

}
