/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'

/**
* The Currency model module.
* @module models/Currency
* @version v2
*/
export default class Currency {
    /**
    * Constructs a new <code>Currency</code>.
    * @alias module:models/Currency
    * @class
    */

    constructor() {
        /**
    *
    * @member {String} isocode
    */
        this.isocode = undefined

    }

    /**
    * Constructs a <code>Currency</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/Currency} obj Optional instance to populate.
    * @return {module:models/Currency} The populated <code>Currency</code>
    * instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Currency()

            if (data.hasOwnProperty('isocode')) {
                obj.isocode = ApiClient.convertToType(data.isocode, 'String')
            }
        }
        return obj
    }

}
