/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The CurrencyModel model module.
* @module models/CurrencyModel
* @version v2
*/
export default class CurrencyModel {
    /**
    * Constructs a new <code>CurrencyModel</code>.
    * @alias module:models/CurrencyModel
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>CurrencyModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CurrencyModel} obj Optional instance to populate.
    * @return {module:models/CurrencyModel} The populated <code>CurrencyModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CurrencyModel();

            
            
            

            if (data.hasOwnProperty('isocode')) {
                obj['isocode'] = ApiClient.convertToType(data['isocode'], 'String');
            }
        }
        return obj;
    }

    /**
    * 
    * @member {String} isocode
    */
    isocode = undefined;








}


