/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import AddressWsDTOModel from './AddressWsDTOModel';
import OrderEntryWsDTOModel from './OrderEntryWsDTOModel';
import PriceWsDTOModel from './PriceWsDTOModel';





/**
* The DeliveryOrderEntryGroupWsDTOModel model module.
* @module models/DeliveryOrderEntryGroupWsDTOModel
* @version v2
*/
export default class DeliveryOrderEntryGroupWsDTOModel {
    /**
    * Constructs a new <code>DeliveryOrderEntryGroupWsDTOModel</code>.
    * @alias module:models/DeliveryOrderEntryGroupWsDTOModel
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>DeliveryOrderEntryGroupWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/DeliveryOrderEntryGroupWsDTOModel} obj Optional instance to populate.
    * @return {module:models/DeliveryOrderEntryGroupWsDTOModel} The populated <code>DeliveryOrderEntryGroupWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeliveryOrderEntryGroupWsDTOModel();

            
            
            

            if (data.hasOwnProperty('deliveryAddress')) {
                obj['deliveryAddress'] = AddressWsDTOModel.constructFromObject(data['deliveryAddress']);
            }
            if (data.hasOwnProperty('totalPriceWithTax')) {
                obj['totalPriceWithTax'] = PriceWsDTOModel.constructFromObject(data['totalPriceWithTax']);
            }
            if (data.hasOwnProperty('entries')) {
                obj['entries'] = ApiClient.convertToType(data['entries'], [OrderEntryWsDTOModel]);
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {module:models/AddressWsDTOModel} deliveryAddress
    */
    deliveryAddress = undefined;
    /**
    * @member {module:models/PriceWsDTOModel} totalPriceWithTax
    */
    totalPriceWithTax = undefined;
    /**
    * 
    * @member {Array.<module:models/OrderEntryWsDTOModel>} entries
    */
    entries = undefined;
    /**
    * 
    * @member {Number} quantity
    */
    quantity = undefined;








}


