/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import SearchState from './SearchState'

/**
* The FacetValue model module.
* @module models/FacetValue
* @version v2
*/
export default class FacetValue {
    /**
    * Constructs a new <code>FacetValue</code>.
    * @alias module:models/FacetValue
    * @class
    */

    constructor() {
        /**
    *
    * @member {String} name
    */
        this.name = undefined
        /**
    *
    * @member {Number} count
    */
        this.count = undefined
        /**
    * @member {module:models/SearchState} query
    */
        this.query = undefined
        /**
    *
    * @member {Boolean} selected
    */
        this.selected = undefined
    }

    /**
    * Constructs a <code>FacetValue</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/FacetValue} obj Optional instance to populate.
    * @return {module:models/FacetValue} The populated
    * <code>FacetValue</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FacetValue()

            if (data.hasOwnProperty('name')) {
                obj.name = ApiClient.convertToType(data.name, 'String')
            }
            if (data.hasOwnProperty('count')) {
                obj.count = ApiClient.convertToType(data.count, 'Number')
            }
            if (data.hasOwnProperty('query')) {
                obj.query = SearchState.constructFromObject(data.query)
            }
            if (data.hasOwnProperty('selected')) {
                obj.selected = ApiClient.convertToType(data.selected, 'Boolean')
            }
        }
        return obj
    }

}
