/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FeatureUnitWsDTO from './FeatureUnitWsDTO';
import FeatureValueWsDTO from './FeatureValueWsDTO';

/**
* The FeatureWsDTO model module.
* @module models/FeatureWsDTO
* @version v2
*/
export default class FeatureWsDTO {
    /**
    * Constructs a new <code>FeatureWsDTO</code>.
    * @alias module:models/FeatureWsDTO
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>FeatureWsDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/FeatureWsDTO} obj Optional instance to populate.
    * @return {module:models/FeatureWsDTO} The populated <code>FeatureWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FeatureWsDTO();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('range')) {
                obj['range'] = ApiClient.convertToType(data['range'], 'Boolean');
            }
            if (data.hasOwnProperty('comparable')) {
                obj['comparable'] = ApiClient.convertToType(data['comparable'], 'Boolean');
            }
            if (data.hasOwnProperty('featureUnit')) {
                obj['featureUnit'] = FeatureUnitWsDTO.constructFromObject(data['featureUnit']);
            }
            if (data.hasOwnProperty('featureValues')) {
                obj['featureValues'] = ApiClient.convertToType(data['featureValues'], [FeatureValueWsDTO]);
            }
        }
        return obj;
    }

    /**
    * 
    * @member {String} code
    */
    code = undefined;
    /**
    * 
    * @member {String} name
    */
    name = undefined;
    /**
    * 
    * @member {String} description
    */
    description = undefined;
    /**
    * 
    * @member {String} type
    */
    type = undefined;
    /**
    * 
    * @member {Boolean} range
    */
    range = undefined;
    /**
    * 
    * @member {Boolean} comparable
    */
    comparable = undefined;
    /**
    * @member {module:models/FeatureUnitWsDTO} featureUnit
    */
    featureUnit = undefined;
    /**
    * 
    * @member {Array.<module:models/FeatureValueWsDTO>} featureValues
    */
    featureValues = undefined;

}
