/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The GeoPointWsDTO model module.
* @module models/GeoPointWsDTO
* @version v2
*/
export default class GeoPointWsDTO {
    /**
    * Constructs a new <code>GeoPointWsDTO</code>.
    * @alias module:models/GeoPointWsDTO
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>GeoPointWsDTO</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/GeoPointWsDTO} obj Optional instance to populate.
    * @return {module:models/GeoPointWsDTO} The populated
    * <code>GeoPointWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GeoPointWsDTO();

            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
        }
        return obj;
    }

    /**
    * 
    * @member {Number} latitude
    */
    latitude = undefined;
    /**
    * 
    * @member {Number} longitude
    */
    longitude = undefined;

}
