/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The LanguageWsDTO model module.
* @module models/LanguageWsDTO
* @version v2
*/
export default class LanguageWsDTO {
    /**
    * Constructs a new <code>LanguageWsDTO</code>.
    * @alias module:models/LanguageWsDTO
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>LanguageWsDTO</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/LanguageWsDTO} obj Optional instance to populate.
    * @return {module:models/LanguageWsDTO} The populated
    * <code>LanguageWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LanguageWsDTO();

            if (data.hasOwnProperty('isocode')) {
                obj['isocode'] = ApiClient.convertToType(data['isocode'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('nativeName')) {
                obj['nativeName'] = ApiClient.convertToType(data['nativeName'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * 
    * @member {String} isocode
    */
    isocode = undefined;
    /**
    * 
    * @member {String} name
    */
    name = undefined;
    /**
    * 
    * @member {String} nativeName
    */
    nativeName = undefined;
    /**
    * 
    * @member {Boolean} active
    */
    active = undefined;

}
