/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import Member from './Member'

/**
* The MemberList model module.
* @module models/MemberList
* @version v2
*/
export default class MemberList {
    /**
    * Constructs a new <code>MemberList</code>.
    * @alias module:models/MemberList
    * @class
    */

    constructor() {
        /**
    *
    * @member {Array.<module:models/Member>} members
    */
        this.members = undefined
    }

    /**
    * Constructs a <code>MemberList</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/MemberList} obj Optional instance to populate.
    * @return {module:models/MemberList} The populated
    * <code>MemberList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberList()

            if (data.hasOwnProperty('members')) {
                obj.members = ApiClient.convertToType(data.members, [Member])
            }
        }
        return obj
    }



}
