/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import DeliveryMode from './DeliveryMode'
import PointOfService from './PointOfService'
import Price from './Price'
import ProductOCC1 from './ProductOCC1'

/**
* The OrderEntry model module.
* @module models/OrderEntry
* @version v2
*/
export default class OrderEntry {
    /**
    * Constructs a new <code>OrderEntry</code>.
    * @alias module:models/OrderEntry
    * @class
    */

    constructor() {
        /**
    *
    * @member {Number} entryNumber
    */
        this.entryNumber = undefined
        /**
    *
    * @member {Number} quantity
    */
        this.quantity = undefined
        /**
    * @member {module:models/Price} basePrice
    */
        this.basePrice = undefined
        /**
    * @member {module:models/Price} totalPrice
    */
        this.totalPrice = undefined
        /**
    * @member {module:models/ProductOCC1} product
    */
        this.product = undefined
        /**
    *
    * @member {Boolean} updateable
    */
        this.updateable = undefined
        /**
    * @member {module:models/DeliveryMode} deliveryMode
    */
        this.deliveryMode = undefined
        /**
    * @member {module:models/PointOfService} deliveryPointOfService
    */
        this.deliveryPointOfService = undefined
    }

    /**
    * Constructs a <code>OrderEntry</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/OrderEntry} obj Optional instance to populate.
    * @return {module:models/OrderEntry} The populated
    * <code>OrderEntry</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderEntry()

            if (data.hasOwnProperty('entryNumber')) {
                obj.entryNumber = ApiClient.convertToType(data.entryNumber, 'Number')
            }
            if (data.hasOwnProperty('quantity')) {
                obj.quantity = ApiClient.convertToType(data.quantity, 'Number')
            }
            if (data.hasOwnProperty('basePrice')) {
                obj.basePrice = Price.constructFromObject(data.basePrice)
            }
            if (data.hasOwnProperty('totalPrice')) {
                obj.totalPrice = Price.constructFromObject(data.totalPrice)
            }
            if (data.hasOwnProperty('product')) {
                obj.product = ProductOCC1.constructFromObject(data.product)
            }
            if (data.hasOwnProperty('updateable')) {
                obj.updateable = ApiClient.convertToType(data.updateable, 'Boolean')
            }
            if (data.hasOwnProperty('deliveryMode')) {
                obj.deliveryMode = DeliveryMode.constructFromObject(data.deliveryMode)
            }
            if (data.hasOwnProperty('deliveryPointOfService')) {
                obj.deliveryPointOfService = PointOfService.constructFromObject(data.deliveryPointOfService)
            }
        }
        return obj
    }



}
