/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import OrderEntry from './OrderEntry'

/**
* The OrderEntryList model module.
* @module models/OrderEntryList
* @version v2
*/
export default class OrderEntryList {
    /**
    * Constructs a new <code>OrderEntryList</code>.
    * @alias module:models/OrderEntryList
    * @class
    */

    constructor() {
        /**
    *
    * @member {Array.<module:models/OrderEntry>} orderEntries
    */
        this.orderEntries = undefined
    }

    /**
    * Constructs a <code>OrderEntryList</code> from a plain JavaScript
    * object, optionally creating a new instance. Copies all relevant properties
    * from <code>data</code> to <code>obj</code> if supplied or a new instance
    * if not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/OrderEntryList} obj Optional instance to
    * populate.
    * @return {module:models/OrderEntryList} The populated
    * <code>OrderEntryList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderEntryList()

            if (data.hasOwnProperty('orderEntries')) {
                obj.orderEntries = ApiClient.convertToType(data.orderEntries, [OrderEntry])
            }
        }
        return obj
    }



}
