/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import DeliveryModeWsDTOModel from './DeliveryModeWsDTOModel';
import PointOfServiceWsDTOModel from './PointOfServiceWsDTOModel';
import PriceWsDTOModel from './PriceWsDTOModel';
import ProductWsDTOModel from './ProductWsDTOModel';





/**
* The OrderEntryWsDTOModel model module.
* @module models/OrderEntryWsDTOModel
* @version v2
*/
export default class OrderEntryWsDTOModel {
    /**
    * Constructs a new <code>OrderEntryWsDTOModel</code>.
    * @alias module:models/OrderEntryWsDTOModel
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>OrderEntryWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/OrderEntryWsDTOModel} obj Optional instance to populate.
    * @return {module:models/OrderEntryWsDTOModel} The populated <code>OrderEntryWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderEntryWsDTOModel();

            
            
            

            if (data.hasOwnProperty('entryNumber')) {
                obj['entryNumber'] = ApiClient.convertToType(data['entryNumber'], 'Number');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('basePrice')) {
                obj['basePrice'] = PriceWsDTOModel.constructFromObject(data['basePrice']);
            }
            if (data.hasOwnProperty('totalPrice')) {
                obj['totalPrice'] = PriceWsDTOModel.constructFromObject(data['totalPrice']);
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = ProductWsDTOModel.constructFromObject(data['product']);
            }
            if (data.hasOwnProperty('updateable')) {
                obj['updateable'] = ApiClient.convertToType(data['updateable'], 'Boolean');
            }
            if (data.hasOwnProperty('deliveryMode')) {
                obj['deliveryMode'] = DeliveryModeWsDTOModel.constructFromObject(data['deliveryMode']);
            }
            if (data.hasOwnProperty('deliveryPointOfService')) {
                obj['deliveryPointOfService'] = PointOfServiceWsDTOModel.constructFromObject(data['deliveryPointOfService']);
            }
        }
        return obj;
    }

    /**
    * 
    * @member {Number} entryNumber
    */
    entryNumber = undefined;
    /**
    * 
    * @member {Number} quantity
    */
    quantity = undefined;
    /**
    * @member {module:models/PriceWsDTOModel} basePrice
    */
    basePrice = undefined;
    /**
    * @member {module:models/PriceWsDTOModel} totalPrice
    */
    totalPrice = undefined;
    /**
    * @member {module:models/ProductWsDTOModel} product
    */
    product = undefined;
    /**
    * 
    * @member {Boolean} updateable
    */
    updateable = undefined;
    /**
    * @member {module:models/DeliveryModeWsDTOModel} deliveryMode
    */
    deliveryMode = undefined;
    /**
    * @member {module:models/PointOfServiceWsDTOModel} deliveryPointOfService
    */
    deliveryPointOfService = undefined;








}


