/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AddressWsDTOModel from './AddressWsDTOModel';
import GeoPointWsDTOModel from './GeoPointWsDTOModel';
import ImageWsDTOModel from './ImageWsDTOModel';
import OpeningScheduleWsDTOModel from './OpeningScheduleWsDTOModel';
import StockWsDTOModel from './StockWsDTOModel';

/**
* The PointOfServiceStockWsDTOModel model module.
* @module models/PointOfServiceStockWsDTOModel
* @version v2
*/
export default class PointOfServiceStockWsDTOModel {
    /**
    * Constructs a new <code>PointOfServiceStockWsDTOModel</code>.
    * @alias module:models/PointOfServiceStockWsDTOModel
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>PointOfServiceStockWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/PointOfServiceStockWsDTOModel} obj Optional instance to populate.
    * @return {module:models/PointOfServiceStockWsDTOModel} The populated <code>PointOfServiceStockWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PointOfServiceStockWsDTOModel();

            if (data.hasOwnProperty('stockInfo')) {
                obj['stockInfo'] = StockWsDTOModel.constructFromObject(data['stockInfo']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('openingHours')) {
                obj['openingHours'] = OpeningScheduleWsDTOModel.constructFromObject(data['openingHours']);
            }
            if (data.hasOwnProperty('storeContent')) {
                obj['storeContent'] = ApiClient.convertToType(data['storeContent'], 'String');
            }
            if (data.hasOwnProperty('features')) {
                obj['features'] = ApiClient.convertToType(data['features'], Object);
            }
            if (data.hasOwnProperty('geoPoint')) {
                obj['geoPoint'] = GeoPointWsDTOModel.constructFromObject(data['geoPoint']);
            }
            if (data.hasOwnProperty('formattedDistance')) {
                obj['formattedDistance'] = ApiClient.convertToType(data['formattedDistance'], 'String');
            }
            if (data.hasOwnProperty('distanceKm')) {
                obj['distanceKm'] = ApiClient.convertToType(data['distanceKm'], 'Number');
            }
            if (data.hasOwnProperty('mapIcon')) {
                obj['mapIcon'] = ImageWsDTOModel.constructFromObject(data['mapIcon']);
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = AddressWsDTOModel.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('storeImages')) {
                obj['storeImages'] = ApiClient.convertToType(data['storeImages'], [ImageWsDTOModel]);
            }
        }
        return obj;
    }

    /**
    * @member {module:models/StockWsDTOModel} stockInfo
    */
    stockInfo = undefined;
    /**
    * 
    * @member {String} name
    */
    name = undefined;
    /**
    * 
    * @member {String} displayName
    */
    displayName = undefined;
    /**
    * 
    * @member {String} url
    */
    url = undefined;
    /**
    * 
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {module:models/OpeningScheduleWsDTOModel} openingHours
    */
    openingHours = undefined;
    /**
    * 
    * @member {String} storeContent
    */
    storeContent = undefined;
    /**
    * 
    * @member {Object} features
    */
    features = undefined;
    /**
    * @member {module:models/GeoPointWsDTOModel} geoPoint
    */
    geoPoint = undefined;
    /**
    * 
    * @member {String} formattedDistance
    */
    formattedDistance = undefined;
    /**
    * 
    * @member {Number} distanceKm
    */
    distanceKm = undefined;
    /**
    * @member {module:models/ImageWsDTOModel} mapIcon
    */
    mapIcon = undefined;
    /**
    * @member {module:models/AddressWsDTOModel} address
    */
    address = undefined;
    /**
    * 
    * @member {Array.<module:models/ImageWsDTOModel>} storeImages
    */
    storeImages = undefined;

}
