/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'

/**
* The PriceWsDTO model module.
* @module models/PriceWsDTO
* @version v2
*/
export default class PriceWsDTO {
    /**
    * Constructs a new <code>PriceWsDTO</code>.
    * @alias module:models/PriceWsDTO
    * @class
    */

    constructor() {
        /**
    *
    * @member {String} currencyIso
    */
        this.currencyIso = undefined
        /**
    *
    * @member {Number} value
    */
        this.value = undefined
        /**
    *
    * @member {String} priceType
    */
        this.priceType = undefined
        /**
    *
    * @member {String} formattedValue
    */
        this.formattedValue = undefined
        /**
    *
    * @member {Number} minQuantity
    */
        this.minQuantity = undefined
        /**
    *
    * @member {Number} maxQuantity
    */
        this.maxQuantity = undefined
    }

    /**
    * Constructs a <code>PriceWsDTO</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/PriceWsDTO} obj Optional instance to populate.
    * @return {module:models/PriceWsDTO} The populated <code>PriceWsDTO</code>
    * instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PriceWsDTO()

            if (data.hasOwnProperty('currencyIso')) {
                obj.currencyIso = ApiClient.convertToType(data.currencyIso, 'String')
            }
            if (data.hasOwnProperty('value')) {
                obj.value = ApiClient.convertToType(data.value, 'Number')
            }
            if (data.hasOwnProperty('priceType')) {
                obj.priceType = ApiClient.convertToType(data.priceType, 'String')
            }
            if (data.hasOwnProperty('formattedValue')) {
                obj.formattedValue = ApiClient.convertToType(data.formattedValue, 'String')
            }
            if (data.hasOwnProperty('minQuantity')) {
                obj.minQuantity = ApiClient.convertToType(data.minQuantity, 'Number')
            }
            if (data.hasOwnProperty('maxQuantity')) {
                obj.maxQuantity = ApiClient.convertToType(data.maxQuantity, 'Number')
            }
        }
        return obj
    }



}
