/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The PriceWsDTOModel model module.
* @module models/PriceWsDTOModel
* @version v2
*/
export default class PriceWsDTOModel {
    /**
    * Constructs a new <code>PriceWsDTOModel</code>.
    * @alias module:models/PriceWsDTOModel
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>PriceWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/PriceWsDTOModel} obj Optional instance to populate.
    * @return {module:models/PriceWsDTOModel} The populated <code>PriceWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PriceWsDTOModel();

            if (data.hasOwnProperty('currencyIso')) {
                obj['currencyIso'] = ApiClient.convertToType(data['currencyIso'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('priceType')) {
                obj['priceType'] = ApiClient.convertToType(data['priceType'], 'String');
            }
            if (data.hasOwnProperty('formattedValue')) {
                obj['formattedValue'] = ApiClient.convertToType(data['formattedValue'], 'String');
            }
            if (data.hasOwnProperty('minQuantity')) {
                obj['minQuantity'] = ApiClient.convertToType(data['minQuantity'], 'Number');
            }
            if (data.hasOwnProperty('maxQuantity')) {
                obj['maxQuantity'] = ApiClient.convertToType(data['maxQuantity'], 'Number');
            }
        }
        return obj;
    }

    /**
    * 
    * @member {String} currencyIso
    */
    currencyIso = undefined;
    /**
    * 
    * @member {Number} value
    */
    value = undefined;
    /**
    * 
    * @member {String} priceType
    */
    priceType = undefined;
    /**
    * 
    * @member {String} formattedValue
    */
    formattedValue = undefined;
    /**
    * 
    * @member {Number} minQuantity
    */
    minQuantity = undefined;
    /**
    * 
    * @member {Number} maxQuantity
    */
    maxQuantity = undefined;

}
