/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import BreadcrumbWsDTO from './BreadcrumbWsDTO'
import FacetWsDTO from './FacetWsDTO'
import PaginationWsDTO from './PaginationWsDTO'
import ProductOCC1 from './ProductOCC1'
import SearchStateWsDTO from './SearchStateWsDTO'
import SortWsDTO from './SortWsDTO'
import SpellingSuggestionWsDTO from './SpellingSuggestionWsDTO'

/**
* The ProductSearchPageWsDTO model module.
* @module models/ProductSearchPageWsDTO
* @version v2
*/
export default class ProductSearchPageWsDTO {
    /**
    * Constructs a new <code>ProductSearchPageWsDTO</code>. POJO containing the
    * result page for product search.
    * @alias module:models/ProductSearchPageWsDTO
    * @class
    */

    constructor() {
        /**
    *
    * @member {String} freeTextSearch
    */
        this.freeTextSearch = undefined
        /**
    *
    * @member {String} categoryCode
    */
        this.categoryCode = undefined
        /**
    *
    * @member {String} keywordRedirectUrl
    */
        this.keywordRedirectUrl = undefined
        /**
    * @member {module:models/SpellingSuggestionWsDTO} spellingSuggestion
    */
        this.spellingSuggestion = undefined
        /**
    *
    * @member {Array.<module:models/ProductOCC1>} products
    */
        this.products = undefined
        /**
    *
    * @member {Array.<module:models/SortWsDTO>} sorts
    */
        this.sorts = undefined
        /**
    * @member {module:models/PaginationWsDTO} pagination
    */
        this.pagination = undefined
        /**
    * @member {module:models/SearchStateWsDTO} currentQuery
    */
        this.currentQuery = undefined
        /**
    *
    * @member {Array.<module:models/BreadcrumbWsDTO>} breadcrumbs
    */
        this.breadcrumbs = undefined
        /**
    *
    * @member {Array.<module:models/FacetWsDTO>} facets
    */
        this.facets = undefined
    }

    /**
    * Constructs a <code>ProductSearchPageWsDTO</code> from a plain JavaScript
    * object, optionally creating a new instance. Copies all relevant properties
    * from <code>data</code> to <code>obj</code> if supplied or a new instance
    * if not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/ProductSearchPageWsDTO} obj Optional instance to
    * populate.
    * @return {module:models/ProductSearchPageWsDTO} The populated
    * <code>ProductSearchPageWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductSearchPageWsDTO()

            if (data.hasOwnProperty('freeTextSearch')) {
                obj.freeTextSearch = ApiClient.convertToType(data.freeTextSearch, 'String')
            }
            if (data.hasOwnProperty('categoryCode')) {
                obj.categoryCode = ApiClient.convertToType(data.categoryCode, 'String')
            }
            if (data.hasOwnProperty('keywordRedirectUrl')) {
                obj.keywordRedirectUrl = ApiClient.convertToType(data.keywordRedirectUrl, 'String')
            }
            if (data.hasOwnProperty('spellingSuggestion')) {
                obj.spellingSuggestion = SpellingSuggestionWsDTO.constructFromObject(data.spellingSuggestion)
            }
            if (data.hasOwnProperty('products')) {
                obj.products = ApiClient.convertToType(data.products, [ProductOCC1])
            }
            if (data.hasOwnProperty('sorts')) {
                obj.sorts = ApiClient.convertToType(data.sorts, [SortWsDTO])
            }
            if (data.hasOwnProperty('pagination')) {
                obj.pagination = PaginationWsDTO.constructFromObject(data.pagination)
            }
            if (data.hasOwnProperty('currentQuery')) {
                obj.currentQuery = SearchStateWsDTO.constructFromObject(data.currentQuery)
            }
            if (data.hasOwnProperty('breadcrumbs')) {
                obj.breadcrumbs = ApiClient.convertToType(data.breadcrumbs, [BreadcrumbWsDTO])
            }
            if (data.hasOwnProperty('facets')) {
                obj.facets = ApiClient.convertToType(data.facets, [FacetWsDTO])
            }
        }
        return obj
    }



}
