/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import ProductReferenceOCC from './ProductReferenceOCC'

/**
* The ProductReferenceListWsDTO model module.
* @module models/ProductReferenceListWsDTO
* @version v2
*/
export default class ProductReferenceListWsDTO {
    /**
    * Constructs a new <code>ProductReferenceListWsDTO</code>.
    * @alias module:models/ProductReferenceListWsDTO
    * @class
    */

    constructor() {
        /**
    *
    * @member {Array.<module:models/ProductReferenceOCC>} references
    */
        this.references = undefined
    }

    /**
    * Constructs a <code>ProductReferenceListWsDTO</code> from a plain
    * JavaScript object, optionally creating a new instance. Copies all relevant
    * properties from <code>data</code> to <code>obj</code> if supplied or a new
    * instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/ProductReferenceListWsDTO} obj Optional instance to
    * populate.
    * @return {module:models/ProductReferenceListWsDTO} The populated
    * <code>ProductReferenceListWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductReferenceListWsDTO()

            if (data.hasOwnProperty('references')) {
                obj.references = ApiClient.convertToType(data.references, [ProductReferenceOCC])
            }
        }
        return obj
    }



}
