/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import ProductExpressUpdateElementWsDTO from './ProductExpressUpdateElementWsDTO'

/**
* The ProductExpressUpdateElementListWsDTO model module.
* @module models/ProductExpressUpdateElementListWsDTO
* @version v2
*/
export default class ProductExpressUpdateElementListWsDTO {
    /**
    * Constructs a new <code>ProductExpressUpdateElementListWsDTO</code>.
    * @alias module:models/ProductExpressUpdateElementListWsDTO
    * @class
    */

    constructor() {
        /**
    *
    * @member {Array.<module:models/ProductExpressUpdateElementWsDTO>}
    * productExpressUpdateElements
    */
        this.productExpressUpdateElements = undefined
    }

    /**
    * Constructs a <code>ProductExpressUpdateElementListWsDTO</code> from a
    * plain JavaScript object, optionally creating a new instance. Copies all
    * relevant properties from <code>data</code> to <code>obj</code> if supplied
    * or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/ProductExpressUpdateElementListWsDTO} obj Optional
    * instance to populate.
    * @return {module:models/ProductExpressUpdateElementListWsDTO} The populated
    * <code>ProductExpressUpdateElementListWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductExpressUpdateElementListWsDTO()

            if (data.hasOwnProperty('productExpressUpdateElements')) {
                obj.productExpressUpdateElements = ApiClient.convertToType(data.productExpressUpdateElements, [ProductExpressUpdateElementWsDTO])
            }
        }
        return obj
    }



}
