/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ProductReferenceWsDTO173Model from './ProductReferenceWsDTO173Model';





/**
* The ProductReferenceListWsDTOModel model module.
* @module models/ProductReferenceListWsDTOModel
* @version v2
*/
export default class ProductReferenceListWsDTOModel {
    /**
    * Constructs a new <code>ProductReferenceListWsDTOModel</code>.
    * @alias module:models/ProductReferenceListWsDTOModel
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ProductReferenceListWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/ProductReferenceListWsDTOModel} obj Optional instance to populate.
    * @return {module:models/ProductReferenceListWsDTOModel} The populated <code>ProductReferenceListWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductReferenceListWsDTOModel();

            
            
            

            if (data.hasOwnProperty('references')) {
                obj['references'] = ApiClient.convertToType(data['references'], [ProductReferenceWsDTO173Model]);
            }
        }
        return obj;
    }

    /**
    * 
    * @member {Array.<module:models/ProductReferenceWsDTO173Model>} references
    */
    references = undefined;








}


