/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import Promotion from './Promotion'

/**
* The PromotionList model module.
* @module models/PromotionList
* @version v2
*/
export default class PromotionList {
    /**
    * Constructs a new <code>PromotionList</code>.
    * @alias module:models/PromotionList
    * @class
    */

    constructor() {
        /**
    *
    * @member {Array.<module:models/Promotion>} promotions
    */
        this.promotions = undefined
    }

    /**
    * Constructs a <code>PromotionList</code> from a plain JavaScript
    * object, optionally creating a new instance. Copies all relevant properties
    * from <code>data</code> to <code>obj</code> if supplied or a new instance
    * if not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/PromotionList} obj Optional instance to
    * populate.
    * @return {module:models/PromotionList} The populated
    * <code>PromotionList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PromotionList()

            if (data.hasOwnProperty('promotions')) {
                obj.promotions = ApiClient.convertToType(data.promotions, [Promotion])
            }
        }
        return obj
    }



}
