/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The PromotionRestrictionWsDTOModel model module.
* @module models/PromotionRestrictionWsDTOModel
* @version v2
*/
export default class PromotionRestrictionWsDTOModel {
    /**
    * Constructs a new <code>PromotionRestrictionWsDTOModel</code>.
    * @alias module:models/PromotionRestrictionWsDTOModel
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>PromotionRestrictionWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/PromotionRestrictionWsDTOModel} obj Optional instance to populate.
    * @return {module:models/PromotionRestrictionWsDTOModel} The populated <code>PromotionRestrictionWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PromotionRestrictionWsDTOModel();

            if (data.hasOwnProperty('restrictionType')) {
                obj['restrictionType'] = ApiClient.convertToType(data['restrictionType'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * 
    * @member {String} restrictionType
    */
    restrictionType = undefined;
    /**
    * 
    * @member {String} description
    */
    description = undefined;

}
