/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import Image from './Image'
import PromotionRestriction from './PromotionRestriction'

/**
* The Promotion model module.
* @module models/Promotion
* @version v2
*/
export default class Promotion {
    /**
    * Constructs a new <code>Promotion</code>.
    * @alias module:models/Promotion
    * @class
    */

    constructor() {
        /**
    *
    * @member {String} code
    */
        this.code = undefined
        /**
    *
    * @member {String} title
    */
        this.title = undefined
        /**
    *
    * @member {String} promotionType
    */
        this.promotionType = undefined
        /**
    *
    * @member {String} startDate
    */
        this.startDate = undefined
        /**
    *
    * @member {String} endDate
    */
        this.endDate = undefined
        /**
    *
    * @member {String} description
    */
        this.description = undefined
        /**
    *
    * @member {Array.<String>} couldFireMessages
    */
        this.couldFireMessages = undefined
        /**
    *
    * @member {Array.<String>} firedMessages
    */
        this.firedMessages = undefined
        /**
    * @member {module:models/Image} productBanner
    */
        this.productBanner = undefined
        /**
    *
    * @member {Boolean} enabled
    */
        this.enabled = undefined
        /**
    *
    * @member {Number} priority
    */
        this.priority = undefined
        /**
    *
    * @member {String} promotionGroup
    */
        this.promotionGroup = undefined
        /**
    *
    * @member {Array.<module:models/PromotionRestriction>} restrictions
    */
        this.restrictions = undefined
    }

    /**
    * Constructs a <code>Promotion</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/Promotion} obj Optional instance to populate.
    * @return {module:models/Promotion} The populated
    * <code>Promotion</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Promotion()

            if (data.hasOwnProperty('code')) {
                obj.code = ApiClient.convertToType(data.code, 'String')
            }
            if (data.hasOwnProperty('title')) {
                obj.title = ApiClient.convertToType(data.title, 'String')
            }
            if (data.hasOwnProperty('promotionType')) {
                obj.promotionType = ApiClient.convertToType(data.promotionType, 'String')
            }
            if (data.hasOwnProperty('startDate')) {
                obj.startDate = ApiClient.convertToType(data.startDate, 'String')
            }
            if (data.hasOwnProperty('endDate')) {
                obj.endDate = ApiClient.convertToType(data.endDate, 'String')
            }
            if (data.hasOwnProperty('description')) {
                obj.description = ApiClient.convertToType(data.description, 'String')
            }
            if (data.hasOwnProperty('couldFireMessages')) {
                obj.couldFireMessages = ApiClient.convertToType(data.couldFireMessages, ['String'])
            }
            if (data.hasOwnProperty('firedMessages')) {
                obj.firedMessages = ApiClient.convertToType(data.firedMessages, ['String'])
            }
            if (data.hasOwnProperty('productBanner')) {
                obj.productBanner = Image.constructFromObject(data.productBanner)
            }
            if (data.hasOwnProperty('enabled')) {
                obj.enabled = ApiClient.convertToType(data.enabled, 'Boolean')
            }
            if (data.hasOwnProperty('priority')) {
                obj.priority = ApiClient.convertToType(data.priority, 'Number')
            }
            if (data.hasOwnProperty('promotionGroup')) {
                obj.promotionGroup = ApiClient.convertToType(data.promotionGroup, 'String')
            }
            if (data.hasOwnProperty('restrictions')) {
                obj.restrictions = ApiClient.convertToType(data.restrictions, [PromotionRestriction])
            }
        }
        return obj
    }



}
