/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import PromotionResult from './PromotionResult'

/**
* The PromotionResultList model module.
* @module models/PromotionResultList
* @version v2
*/
export default class PromotionResultList {
    /**
    * Constructs a new <code>PromotionResultList</code>.
    * @alias module:models/PromotionResultList
    * @class
    */

    constructor() {
        /**
    *
    * @member {Array.<module:models/PromotionResult>} promotions
    */
        this.promotions = undefined
    }

    /**
    * Constructs a <code>PromotionResultList</code> from a plain JavaScript
    * object, optionally creating a new instance. Copies all relevant properties
    * from <code>data</code> to <code>obj</code> if supplied or a new instance
    * if not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/PromotionResultList} obj Optional instance to
    * populate.
    * @return {module:models/PromotionResultList} The populated
    * <code>PromotionResultList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PromotionResultList()

            if (data.hasOwnProperty('promotions')) {
                obj.promotions = ApiClient.convertToType(data.promotions, [PromotionResult])
            }
        }
        return obj
    }



}
