/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReviewWsDTO from './ReviewWsDTO';

/**
* The ReviewListWsDTO model module.
* @module models/ReviewListWsDTO
* @version v2
*/
export default class ReviewListWsDTO {
    /**
    * Constructs a new <code>ReviewListWsDTO</code>.
    * @alias module:models/ReviewListWsDTO
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>ReviewListWsDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/ReviewListWsDTO} obj Optional instance to populate.
    * @return {module:models/ReviewListWsDTO} The populated <code>ReviewListWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReviewListWsDTO();

            if (data.hasOwnProperty('reviews')) {
                obj['reviews'] = ApiClient.convertToType(data['reviews'], [ReviewWsDTO]);
            }
        }
        return obj;
    }

    /**
    * 
    * @member {Array.<module:models/ReviewWsDTO>} reviews
    */
    reviews = undefined;

}
