/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import Cart from './Cart'

/**
* The SaveCartResult model module.
* @module models/SaveCartResult
* @version v2
*/
export default class SaveCartResult {
    /**
    * Constructs a new <code>SaveCartResult</code>.
    * @alias module:models/SaveCartResult
    * @class
    */

    constructor() {
        /**
    * @member {module:models/Cart} savedCartData
    */
        this.savedCartData = undefined
    }

    /**
    * Constructs a <code>SaveCartResult</code> from a plain JavaScript
    * object, optionally creating a new instance. Copies all relevant properties
    * from <code>data</code> to <code>obj</code> if supplied or a new instance
    * if not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/SaveCartResult} obj Optional instance to
    * populate.
    * @return {module:models/SaveCartResult} The populated
    * <code>SaveCartResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SaveCartResult()

            if (data.hasOwnProperty('savedCartData')) {
                obj.savedCartData = Cart.constructFromObject(data.savedCartData)
            }
        }
        return obj
    }

}
