/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'

/**
* The SortWsDTO model module.
* @module models/SortWsDTO
* @version v2
*/
export default class SortWsDTO {
    /**
    * Constructs a new <code>SortWsDTO</code>.
    * @alias module:models/SortWsDTO
    * @class
    */

    constructor() {
        /**
    *
    * @member {String} code
    */
        this.code = undefined
        /**
    *
    * @member {String} name
    */
        this.name = undefined
        /**
    *
    * @member {Boolean} selected
    */
        this.selected = undefined
    }

    /**
    * Constructs a <code>SortWsDTO</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/SortWsDTO} obj Optional instance to populate.
    * @return {module:models/SortWsDTO} The populated <code>SortWsDTO</code>
    * instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SortWsDTO()

            if (data.hasOwnProperty('code')) {
                obj.code = ApiClient.convertToType(data.code, 'String')
            }
            if (data.hasOwnProperty('name')) {
                obj.name = ApiClient.convertToType(data.name, 'String')
            }
            if (data.hasOwnProperty('selected')) {
                obj.selected = ApiClient.convertToType(data.selected, 'Boolean')
            }
        }
        return obj
    }



}
