/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TimeWsDTO from './TimeWsDTO';

/**
* The SpecialOpeningDayWsDTO model module.
* @module models/SpecialOpeningDayWsDTO
* @version v2
*/
export default class SpecialOpeningDayWsDTO {
    /**
    * Constructs a new <code>SpecialOpeningDayWsDTO</code>.
    * @alias module:models/SpecialOpeningDayWsDTO
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>SpecialOpeningDayWsDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/SpecialOpeningDayWsDTO} obj Optional instance to populate.
    * @return {module:models/SpecialOpeningDayWsDTO} The populated <code>SpecialOpeningDayWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpecialOpeningDayWsDTO();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('formattedDate')) {
                obj['formattedDate'] = ApiClient.convertToType(data['formattedDate'], 'String');
            }
            if (data.hasOwnProperty('closed')) {
                obj['closed'] = ApiClient.convertToType(data['closed'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('openingTime')) {
                obj['openingTime'] = TimeWsDTO.constructFromObject(data['openingTime']);
            }
            if (data.hasOwnProperty('closingTime')) {
                obj['closingTime'] = TimeWsDTO.constructFromObject(data['closingTime']);
            }
        }
        return obj;
    }

    /**
    * 
    * @member {String} date
    */
    date = undefined;
    /**
    * 
    * @member {String} formattedDate
    */
    formattedDate = undefined;
    /**
    * 
    * @member {Boolean} closed
    */
    closed = undefined;
    /**
    * 
    * @member {String} name
    */
    name = undefined;
    /**
    * 
    * @member {String} comment
    */
    comment = undefined;
    /**
    * @member {module:models/TimeWsDTO} openingTime
    */
    openingTime = undefined;
    /**
    * @member {module:models/TimeWsDTO} closingTime
    */
    closingTime = undefined;

}
