/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'

/**
* The SpellingSuggestionWsDTO model module.
* @module models/SpellingSuggestionWsDTO
* @version v2
*/
export default class SpellingSuggestionWsDTO {
    /**
    * Constructs a new <code>SpellingSuggestionWsDTO</code>.
    * @alias module:models/SpellingSuggestionWsDTO
    * @class
    */

    constructor() {
        /**
    *
    * @member {String} suggestion
    */
        this.suggestion = undefined
        /**
    *
    * @member {String} query
    */
        this.query = undefined
    }

    /**
    * Constructs a <code>SpellingSuggestionWsDTO</code> from a plain JavaScript
    * object, optionally creating a new instance. Copies all relevant properties
    * from <code>data</code> to <code>obj</code> if supplied or a new instance
    * if not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/SpellingSuggestionWsDTO} obj Optional instance to
    * populate.
    * @return {module:models/SpellingSuggestionWsDTO} The populated
    * <code>SpellingSuggestionWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpellingSuggestionWsDTO()

            if (data.hasOwnProperty('suggestion')) {
                obj.suggestion = ApiClient.convertToType(data.suggestion, 'String')
            }
            if (data.hasOwnProperty('query')) {
                obj.query = ApiClient.convertToType(data.query, 'String')
            }
        }
        return obj
    }



}
