/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The StockWsDTOModel model module.
* @module models/StockWsDTOModel
* @version v2
*/
export default class StockWsDTOModel {
    /**
    * Constructs a new <code>StockWsDTOModel</code>.
    * @alias module:models/StockWsDTOModel
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>StockWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/StockWsDTOModel} obj Optional instance to populate.
    * @return {module:models/StockWsDTOModel} The populated <code>StockWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StockWsDTOModel();

            
            
            

            if (data.hasOwnProperty('stockLevelStatus')) {
                obj['stockLevelStatus'] = ApiClient.convertToType(data['stockLevelStatus'], 'String');
            }
            if (data.hasOwnProperty('stockLevel')) {
                obj['stockLevel'] = ApiClient.convertToType(data['stockLevel'], 'Number');
            }
        }
        return obj;
    }

    /**
    * 
    * @member {String} stockLevelStatus
    */
    stockLevelStatus = undefined;
    /**
    * 
    * @member {Number} stockLevel
    */
    stockLevel = undefined;








}


