/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import SuggestionWsDTO from './SuggestionWsDTO'

/**
* The SuggestionListWsDTO model module.
* @module models/SuggestionListWsDTO
* @version v2
*/
export default class SuggestionListWsDTO {
    /**
    * Constructs a new <code>SuggestionListWsDTO</code>.
    * @alias module:models/SuggestionListWsDTO
    * @class
    */

    constructor() {
        /**
    *
    * @member {Array.<module:models/SuggestionWsDTO>} suggestions
    */
        this.suggestions = undefined
    }

    /**
    * Constructs a <code>SuggestionListWsDTO</code> from a plain JavaScript
    * object, optionally creating a new instance. Copies all relevant properties
    * from <code>data</code> to <code>obj</code> if supplied or a new instance
    * if not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/SuggestionListWsDTO} obj Optional instance to
    * populate.
    * @return {module:models/SuggestionListWsDTO} The populated
    * <code>SuggestionListWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SuggestionListWsDTO()

            if (data.hasOwnProperty('suggestions')) {
                obj.suggestions = ApiClient.convertToType(data.suggestions, [SuggestionWsDTO])
            }
        }
        return obj
    }



}
