/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SuggestionWsDTOModel from './SuggestionWsDTOModel';

/**
* The SuggestionListWsDTOModel model module.
* @module models/SuggestionListWsDTOModel
* @version v2
*/
export default class SuggestionListWsDTOModel {
    /**
    * Constructs a new <code>SuggestionListWsDTOModel</code>.
    * @alias module:models/SuggestionListWsDTOModel
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>SuggestionListWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/SuggestionListWsDTOModel} obj Optional instance to populate.
    * @return {module:models/SuggestionListWsDTOModel} The populated <code>SuggestionListWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SuggestionListWsDTOModel();

            if (data.hasOwnProperty('suggestions')) {
                obj['suggestions'] = ApiClient.convertToType(data['suggestions'], [SuggestionWsDTOModel]);
            }
        }
        return obj;
    }

    /**
    * 
    * @member {Array.<module:models/SuggestionWsDTOModel>} suggestions
    */
    suggestions = undefined;

}
