/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TimeWsDTOModel model module.
* @module models/TimeWsDTOModel
* @version v2
*/
export default class TimeWsDTOModel {
    /**
    * Constructs a new <code>TimeWsDTOModel</code>.
    * @alias module:models/TimeWsDTOModel
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TimeWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/TimeWsDTOModel} obj Optional instance to populate.
    * @return {module:models/TimeWsDTOModel} The populated <code>TimeWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimeWsDTOModel();

            
            
            

            if (data.hasOwnProperty('hour')) {
                obj['hour'] = ApiClient.convertToType(data['hour'], 'String');
            }
            if (data.hasOwnProperty('minute')) {
                obj['minute'] = ApiClient.convertToType(data['minute'], 'String');
            }
            if (data.hasOwnProperty('formattedHour')) {
                obj['formattedHour'] = ApiClient.convertToType(data['formattedHour'], 'String');
            }
        }
        return obj;
    }

    /**
    * 
    * @member {String} hour
    */
    hour = undefined;
    /**
    * 
    * @member {String} minute
    */
    minute = undefined;
    /**
    * 
    * @member {String} formattedHour
    */
    formattedHour = undefined;








}


