/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import VariantCategoryWsDTOModel from './VariantCategoryWsDTOModel';





/**
* The VariantValueCategoryWsDTOModel model module.
* @module models/VariantValueCategoryWsDTOModel
* @version v2
*/
export default class VariantValueCategoryWsDTOModel {
    /**
    * Constructs a new <code>VariantValueCategoryWsDTOModel</code>.
    * @alias module:models/VariantValueCategoryWsDTOModel
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>VariantValueCategoryWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/VariantValueCategoryWsDTOModel} obj Optional instance to populate.
    * @return {module:models/VariantValueCategoryWsDTOModel} The populated <code>VariantValueCategoryWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VariantValueCategoryWsDTOModel();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('sequence')) {
                obj['sequence'] = ApiClient.convertToType(data['sequence'], 'Number');
            }
            if (data.hasOwnProperty('superCategories')) {
                obj['superCategories'] = ApiClient.convertToType(data['superCategories'], [VariantCategoryWsDTOModel]);
            }
        }
        return obj;
    }

    /**
    * 
    * @member {String} name
    */
    name = undefined;
    /**
    * 
    * @member {Number} sequence
    */
    sequence = undefined;
    /**
    * 
    * @member {Array.<module:models/VariantCategoryWsDTOModel>} superCategories
    */
    superCategories = undefined;








}


