/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PriceWsDTOModel from './PriceWsDTOModel';
import StockWsDTOModel from './StockWsDTOModel';
import VariantOptionQualifierWsDTOModel from './VariantOptionQualifierWsDTOModel';

/**
* The VariantOptionWsDTOModel model module.
* @module models/VariantOptionWsDTOModel
* @version v2
*/
export default class VariantOptionWsDTOModel {
    /**
    * Constructs a new <code>VariantOptionWsDTOModel</code>.
    * @alias module:models/VariantOptionWsDTOModel
    * @class
    */

    constructor() {
        
    }

    /**
    * Constructs a <code>VariantOptionWsDTOModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/VariantOptionWsDTOModel} obj Optional instance to populate.
    * @return {module:models/VariantOptionWsDTOModel} The populated <code>VariantOptionWsDTOModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VariantOptionWsDTOModel();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('stock')) {
                obj['stock'] = StockWsDTOModel.constructFromObject(data['stock']);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('priceData')) {
                obj['priceData'] = PriceWsDTOModel.constructFromObject(data['priceData']);
            }
            if (data.hasOwnProperty('variantOptionQualifiers')) {
                obj['variantOptionQualifiers'] = ApiClient.convertToType(data['variantOptionQualifiers'], [VariantOptionQualifierWsDTOModel]);
            }
        }
        return obj;
    }

    /**
    * 
    * @member {String} code
    */
    code = undefined;
    /**
    * @member {module:models/StockWsDTOModel} stock
    */
    stock = undefined;
    /**
    * 
    * @member {String} url
    */
    url = undefined;
    /**
    * @member {module:models/PriceWsDTOModel} priceData
    */
    priceData = undefined;
    /**
    * 
    * @member {Array.<module:models/VariantOptionQualifierWsDTOModel>} variantOptionQualifiers
    */
    variantOptionQualifiers = undefined;

}
