/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import CurrencyWsDTO from './CurrencyWsDTO'
import PriceWsDTO from './PriceWsDTO'

/**
* The VoucherWsDTO model module.
* @module models/VoucherWsDTO
* @version v2
*/
export default class VoucherWsDTO {
    /**
    * Constructs a new <code>VoucherWsDTO</code>.
    * @alias module:models/VoucherWsDTO
    * @class
    */

    constructor() {
        /**
    *
    * @member {String} code
    */
        this.code = undefined
        /**
    *
    * @member {String} voucherCode
    */
        this.voucherCode = undefined
        /**
    *
    * @member {String} name
    */
        this.name = undefined
        /**
    *
    * @member {String} description
    */
        this.description = undefined
        /**
    *
    * @member {Number} value
    */
        this.value = undefined
        /**
    *
    * @member {String} valueFormatted
    */
        this.valueFormatted = undefined
        /**
    *
    * @member {String} valueString
    */
        this.valueString = undefined
        /**
    *
    * @member {Boolean} freeShipping
    */
        this.freeShipping = undefined
        /**
    * @member {module:models/CurrencyWsDTO} currency
    */
        this.currency = undefined
        /**
    * @member {module:models/PriceWsDTO} appliedValue
    */
        this.appliedValue = undefined
    }

    /**
    * Constructs a <code>VoucherWsDTO</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/VoucherWsDTO} obj Optional instance to populate.
    * @return {module:models/VoucherWsDTO} The populated
    * <code>VoucherWsDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VoucherWsDTO()

            if (data.hasOwnProperty('code')) {
                obj.code = ApiClient.convertToType(data.code, 'String')
            }
            if (data.hasOwnProperty('voucherCode')) {
                obj.voucherCode = ApiClient.convertToType(data.voucherCode, 'String')
            }
            if (data.hasOwnProperty('name')) {
                obj.name = ApiClient.convertToType(data.name, 'String')
            }
            if (data.hasOwnProperty('description')) {
                obj.description = ApiClient.convertToType(data.description, 'String')
            }
            if (data.hasOwnProperty('value')) {
                obj.value = ApiClient.convertToType(data.value, 'Number')
            }
            if (data.hasOwnProperty('valueFormatted')) {
                obj.valueFormatted = ApiClient.convertToType(data.valueFormatted, 'String')
            }
            if (data.hasOwnProperty('valueString')) {
                obj.valueString = ApiClient.convertToType(data.valueString, 'String')
            }
            if (data.hasOwnProperty('freeShipping')) {
                obj.freeShipping = ApiClient.convertToType(data.freeShipping, 'Boolean')
            }
            if (data.hasOwnProperty('currency')) {
                obj.currency = CurrencyWsDTO.constructFromObject(data.currency)
            }
            if (data.hasOwnProperty('appliedValue')) {
                obj.appliedValue = PriceWsDTO.constructFromObject(data.appliedValue)
            }
        }
        return obj
    }



}
