/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 *
 */

import ApiClient from '../ApiClient'
import Voucher from './Voucher'

/**
* The VoucherList model module.
* @module models/VoucherList
* @version v2
*/
export default class VoucherList {
    /**
    * Constructs a new <code>VoucherList</code>.
    * @alias module:models/VoucherList
    * @class
    */

    constructor() {
        /**
    *
    * @member {Array.<module:models/Voucher>} vouchers
    */
        this.vouchers = undefined
    }

    /**
    * Constructs a <code>VoucherList</code> from a plain JavaScript object,
    * optionally creating a new instance. Copies all relevant properties from
    * <code>data</code> to <code>obj</code> if supplied or a new instance if
    * not.
    * @param {Object} data The plain JavaScript object bearing properties of
    * interest.
    * @param {module:models/VoucherList} obj Optional instance to populate.
    * @return {module:models/VoucherList} The populated
    * <code>VoucherList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VoucherList()

            if (data.hasOwnProperty('vouchers')) {
                obj.vouchers = ApiClient.convertToType(data.vouchers, [Voucher])
            }
        }
        return obj
    }



}
