/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import expect from 'expect.js'
import Occ from '../config'

let instance
const {promotion} = Occ

beforeEach(() => {
    instance = new Occ.PromotionsApi()
})

describe('PromotionsApi', () => {
    describe('getPromotions', () => {
        it('should call getPromotions successfully', (done) => {
            instance.getPromotions({promotionGroup: promotion.group, type: 'all'})
                .then((res) => {
                    expect(res).to.have.property('promotions')
                    done()
                })
        })
    })
    describe('getPromotion', () => {
        it('should call getPromotion successfully', (done) => {
            instance.getPromotion(promotion.code)
                .then((res) => {
                    expect(res.code).to.equal(promotion.code)
                    done()
                })
        })
    })
})
