/**
 * OCC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../config'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../config'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Occ);
  }
}(this, function(expect, Occ) {
  'use strict';

  var instance;
  const {promotion} = Occ.default

  beforeEach(function() {
    instance = new Occ.default.PromotionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PromotionsApi', function() {
    describe('getPromotions', function() {
      it('should call getPromotions successfully', function(done) {
        instance.getPromotions({promotionGroup: promotion.group, type: 'all'})
          .then((res) => {
            expect(res).to.have.property('promotions');
            done();
          })
      });
    });
    describe('getPromotion', function() {
      it('should call getPromotion successfully', function(done) {
        instance.getPromotion(promotion.code)
          .then((res) => {
            expect(res.code).to.equal(promotion.code);
            done();
          })
      });
    });
  });

}));
